### ISSUE TITLE
Initialization time

### ISSUE THREAD

**Issue by false** [ufrisk/MemProcFS#12]
Hi,

The problem might be more a leechcore issue, I am not sure but as I m using the top level vmm init so I am posting here.

When I used 3.2/3.4 + pcileech, init time was around 3 seconds. Since I moved to leechcore + vmm, just the vmm init call takes around 20-25s. Is that a normal behavior ? I use the -device fpga arguments.

**Comment by ufrisk** [comment]
are you using the most recent version of vmm.dll / leechcore.dll - this looks like an issue I fixed in last release

**Comment by false** [comment]
I have checked and decided to compile leechcore.dll (version 1.5.1, commit 202040c886c05f947483b01530619b98e2d7116c) and vmm.dll (version 2.10.2, commit 69c2a5767e9beee84727ce75cb93dcbd96fa1f01) and I still have the issue ; The VMMDLL_Initialize takes around 18 seconds. The project is in C++, 64 bits and this is how I call it : 
	```
LPSTR args[3];
	args[0] = "";
	args[1] = "-device";
	args[2] = "fpga";
	result = VMMDLL_Initialize(3, args);
```

**Comment by ufrisk** [comment]
Can you please do a a memory dump with `pcileech dump` command and check if the problem persists when opening the dump file.

If so are you able to share this dump file? please note that dump files may contain sensitive information such as passwords.

**Comment by false** [comment]
Yes of course. If it can contain sensible information I would prefer to send it on your email if it's ok with you ?

**Comment by ufrisk** [comment]
yes, an email with the link to it will be fine :)

**Comment by false** [comment]
Ok, I have compiled a new bitstream using last 4.0 commit, and indeed it went from 20s to less than 3s, so problem solved actually. That way I am not sure which bitstream I was using which lead to this issue ; I think it was a compiled version from the 4.0 release sources but as I ve just said I'm really not sure anymore. Thanks for help :-)
